insert into QUOTE (
	id,
	quote
) values
	(default, 'You can observe a lot just by watching.'),
	(default, 'You better cut the pizza in four pieces because I’m not hungry enough to eat six.'),
	(default, 'I take a two hour nap, from one o''clock to four.'),
	(default, 'I always knew that record would stand until it was broken.'),
	(default, 'We made too many wrong mistakes.'),
	(default, 'You give 100 percent in the first half of the game, and if that isn''t enough in the second half you give what''s left.'),
	(default, 'You should always go to other people''s funerals; otherwise, they won''t come to yours.'),
	(default, 'It ain''t the heat; it’s the humility.'),
	(default, 'He can run anytime he wants. I’m giving him the red light.'),
	(default, 'If people don''t want to come out to the ball park, how you gonna stop them?'),
	(default, 'Thanks, you don''t look so hot yourself. After being told he looked nice and cool.'),
	(default, 'I knew I was going to take the wrong train, so I left early.'),
	(default, 'Baseball is 90% mental... the other half is physical.'),
	(default, 'The towels were so thick there... I could hardly close my suitcase.'),
	(default, 'Why buy good luggage? You only use it when you travel.'),
	(default, '90% of the putts that are short don’t go in.'),
	(default, 'You''ve got to be very careful if you don''t know where you''re going, because you might not get there.'),
	(default, 'Nobody goes there anymore; it''s too crowded.'),
	(default, 'Slump? I ain''t in no slump. I just ain''t hitting.'),
	(default, 'That''s his style of hitting. If you can''t imitate him, don''t copy him.'),
	(default, 'I never blame myself when I''m not hitting. I just blame the bat, and if it keeps up, I change bats. After all, if I know it isn''t my fault that I''m not hitting, how can I get mad at myself?'),
	(default, 'The other teams could make trouble for us if they win.'),
	(default, 'It''s never happened in the World Series competition, and it still hasn''t.'),
	(default, 'I’d find the fellow who lost it, and, if he was poor, I''d return it.'),
	(default, 'Think! How the hell are you gonna think and hit at the same time?'),
	(default, 'It was impossible to get a conversation going; everybody was talking too much.'),
	(default, 'If you come to a fork in the road, take it.'),
	(default, 'A nickel ain''t worth a dime anymore.'),
	(default, 'If you don''t know where you are going, you will wind up somewhere else.'),
	(default, 'All pitchers are liars or crybabies.'),
	(default, 'In theory there is no difference between theory and practice. In practice there is.'),
	(default, 'Nobody can be all smiley all the time, but having a good positive attitude isn''t something to shrug off.'),
	(default, 'It ain''t over ''til it''s over.'),
	(default, 'Swing at the strikes.'),
	(default, 'He hits from both sides of the plate. He''s amphibious.'),
	(default, 'I can see how he (Sandy Koufax) won 25 games. What I don''t understand is how he lost 5.'),
	(default, 'I''m not gonna buy my kids an encyclopedia. Let them walk to school like I did.'),
	(default, 'In baseball you don''t know nothing.'),
	(default, 'I think Little League is wonderful. It keeps the kids out of the house.'),
	(default, 'I wish everybody had the drive he (Joe DiMaggio) had. He never did nothing wrong on the field. I never seen him dive for the ball... everything was a waist-high catch... and he never walked off the field.'),
	(default, 'So I''m ugly. I never saw nobody hit with his face..'),
	(default, 'Take it with a grin of salt.'),
	(default, 'If we didn''t want to bring him up we might as well have let him stay down.'),
	(default, 'We''ve had enough trowels and tribulations.'),
	(default, 'Never answer an anonymous letter.'),
	(default, 'Little League is good because it keeps the parents off the streets.'),
	(default, 'When I was young and green behind the ears.'),
	(default, 'If the world were perfect, it wouldn''t be.'),
	(default, 'A home opener is always exciting, whether it''s at home or on the road.'),
	(default, 'If you don''t catch the ball you catch the bus home.'),
	(default, 'I never said most of the things I said.'),
	(default, 'He was a big clog in their machine.'),
	(default, 'It’s not too far. It just seems like it is.');
