INSERT INTO quote (play, quote) VALUES
('Hamlet', 'To be, or not to be: that is the question.'),
('As You Like It', 'All the world''s a stage, and all the men and women merely players.'),
('Hamlet', 'Brevity is the soul of wit.'),
('Romeo and Juliet', 'Romeo, Romeo, wherefore art thou Romeo?'),
('A Midsummer Night''s Dream', 'The course of true love never did run smooth.'),
('Julius Caesar', CONCAT('Cowards die many times before their deaths', CHAR(59), ' the valiant never taste of death but once.')),
('Twelfth Night', 'If music be the food of love, play on.'),
('The Tempest', CONCAT('We are such stuff as dreams are made on', CHAR(59), ' and our little life is rounded with a sleep.')),
('The Merchant of Venice', 'The quality of mercy is not strained.'),
('Macbeth', 'Fair is foul, and foul is fair.'),
('Much Ado About Nothing', 'I do love nothing in the world so well as you: is not that strange?'),
('Henry V', 'We few, we happy few, we band of brothers.'),
('King Lear', 'How sharper than a serpent''s tooth it is to have a thankless child!'),
('Othello', 'O, beware, my lord, of jealousy! It is the green-eyed monster which doth mock the meat it feeds on.'),
('Richard III', 'Now is the winter of our discontent made glorious summer by this sun of York.'),
('Antony and Cleopatra', 'Age cannot wither her, nor custom stale her infinite variety.'),
('Macbeth', 'Out, damned spot! out, I say!'),
('Romeo and Juliet', 'A plague o'' both your houses!'),
('Hamlet', 'Though this be madness, yet there is method in it.'),
('Twelfth Night', 'Some are born great, some achieve greatness, and some have greatness thrust upon them.'),
('As You Like It', 'The fool doth think he is wise, but the wise man knows himself to be a fool.'),
('Measure for Measure', 'Our doubts are traitors and make us lose the good we oft might win by fearing to attempt.'),
('Henry VI, Part 2', 'The first thing we do, let''s kill all the lawyers.'),
('Macbeth', CONCAT('Double, double toil and trouble', CHAR(59), ' fire burn, and cauldron bubble.')),
('Julius Caesar', 'Et tu, Brute? Then fall, Caesar.');
INSERT INTO quote (play, quote) VALUES
('The Two Gentlemen of Verona', 'They do not love that do not show their love.'),
('Macbeth', CONCAT('Stars, hide your fires', CHAR(59), ' let not light see my black and deep desires.')),
('Cymbeline', 'The game is up.'),
('Hamlet', 'I must be cruel, only to be kind.'),
('The Taming of the Shrew', 'And thereby hangs a tale.'),
('Antony and Cleopatra', 'My salad days, when I was green in judgment: cold in blood.'),
('Troilus and Cressida', 'The common curse of mankind, folly and ignorance.'),
('Othello', 'Tis neither here nor there.'),
('A Midsummer Night''s Dream', 'Lord, what fools these mortals be!'),
('King Lear', 'The wheel is come full circle: I am here.'),
('Julius Caesar', 'Cry havoc and let slip the dogs of war.'),
('The Comedy of Errors', 'Small cheer and great welcome makes a merry feast.'),
('Twelfth Night', 'Dost thou think, because thou art virtuous, there shall be no more cakes and ale?'),
('As You Like It', 'I like this place and willingly could waste my time in it.'),
('Coriolanus', 'Nature teaches beasts to know their friends.'),
('Henry IV, Part 1', 'I am as vigilant as a cat to steal cream.'),
('The Tempest', 'Misery acquaints a man with strange bedfellows.'),
('Romeo and Juliet', 'For you and I are past our dancing days.'),
('Hamlet', 'The time is out of joint: O cursed spite, that ever I was born to set it right!'),
('Richard II', 'I wasted time, and now doth time waste me.'),
('The Taming of the Shrew', 'There''s small choice in rotten apples.'),
('The Winter''s Tale', 'What''s gone and what''s past help should be past grief.'),
('Henry IV, Part 2', 'He hath eaten me out of house and home.'),
('The Merry Wives of Windsor', 'This is the short and the long of it.'),
('Hamlet', 'Sweets to the sweet: farewell!');
INSERT INTO quote (play, quote) VALUES
('Julius Caesar', CONCAT('Friends, Romans, countrymen, lend me your ears', CHAR(59), ' I come to bury Caesar, not to praise him.')),
('The Comedy of Errors', 'A wretched soul, bruised with adversity, we bid be quiet when we hear it cry.'),
('Romeo and Juliet', 'O, swear not by the moon, the inconstant moon, that monthly changes in her circled orb.'),
('King John', 'To gild refined gold, to paint the lily, to throw a perfume on the violet.'),
('Hamlet', CONCAT('Give every man thy ear, but few thy voice', CHAR(59), ' take each man''s censure, but reserve thy judgment.')),
('The Winter''s Tale', 'A sad tale''s best for winter: I have one of sprites and goblins.'),
('Macbeth', 'Come, seeling night, scarf up the tender eye of pitiful day.'),
('King Lear', 'Thou shouldst not have been old till thou hadst been wise.'),
('The Merchant of Venice', 'I am not bound to please thee with my answers.'),
('Othello', 'Good name in man and woman, dear my lord, is the immediate jewel of their souls.'),
('Romeo and Juliet', 'See, how she leans her cheek upon her hand! O that I were a glove upon that hand, that I might touch that cheek!'),
('Henry VIII', CONCAT('Men''s evil manners live in brass', CHAR(59), ' their virtues we write in water.')),
('As You Like It', 'Men have died from time to time, and worms have eaten them, but not for love.'),
('The Merchant of Venice', CONCAT('I hold the world but as the world, Gratiano', CHAR(59), ' a stage where every man must play a part, and mine a sad one.')),
('King Lear', 'I will do such things, what they are, yet I know not: but they shall be the terrors of the earth.'),
('Hamlet', CONCAT('To die, to sleep', CHAR(59), ' to sleep: perchance to dream: ay, there''s the rub.')),
('Romeo and Juliet', CONCAT('Wisely and slow', CHAR(59), ' they stumble that run fast.')),
('The Merry Wives of Windsor', 'Why, then the world''s mine oyster, which I with sword will open.'),
('Twelfth Night', 'Love sought is good, but given unsought, is better.'),
('The Tempest', 'Our revels now are ended. These our actors, as I foretold you, were all spirits and are melted into air, into thin air.'),
('As You Like It', 'I had rather have a fool to make me merry than experience to make me sad.'),
('Macbeth', 'When shall we three meet again in thunder, lightning, or in rain?'),
('Hamlet', 'This above all: to thine own self be true, and it must follow, as the night the day, thou canst not then be false to any man.'),
('Othello', CONCAT('The robbed that smiles steals something from the thief', CHAR(59), 'he robs himself that spends a bootless grief.')),
('Richard II', 'Not all the water in the rough rude sea can wash the balm off from an anointed king.');
