insert into QUOTE (
	id,
        type,
	quote
) values
	(default, 2, 'Dad always thought laughter was the best medicine, which I guess is why several of us died of tuberculosis.'),
	(default, 2, 'Maybe in order to understand mankind, we have to look at the word itself: "Mankind". Basically, it''s made up of two separate words - "mank" and "ind". What do these words mean ? It''s a mystery, and that''s why so is mankind.'),
	(default, 2, 'I hope if dogs ever take over the world, and they chose a king, they don''t just go by size, because I bet there are some Chihuahuas with some good ideas.'),
	(default, 2, 'It takes a big man to cry, but it takes a bigger man to laugh at that man.'),
	(default, 2, 'I guess we were all guilty, in a way. We all shot him, we all skinned him, and we all got a complimentary bumper sticker that said, "I helped skin Bob."'),
	(default, 2, 'I bet the main reason the police keep people away from a plane crash is they don''t want anybody walking in and lying down in the crash stuff, then, when somebody comes up, act like they just woke up and go, "What was THAT?!"'),
	(default, 2, 'The face of a child can say it all, especially the mouth part of the face.'),
	(default, 2, 'Ambition is like a frog sitting on a Venus Flytrap. The flytrap can bite and bite, but it won''t bother the frog because it only has little tiny plant teeth. But some other stuff could happen and it could be like ambition.'),
	(default, 2, 'I''d rather be rich than stupid.'),
	(default, 2, 'If you were a poor Indian with no weapons, and a bunch of conquistadors came up to you and asked where the gold was, I don''t think it would be a good idea to say, "I swallowed it. So sue me."'),
	(default, 2, 'If you define cowardice as running away at the first sign of danger, screaming and tripping and begging for mercy, then yes, Mr. Brave man, I guess I''m a coward.'),
	(default, 2, 'I bet one legend that keeps recurring throughout history, in every culture, is the story of Popeye.'),
	(default, 2, 'When you go in for a job interview, I think a good thing to ask is if they ever press charges.'),
	(default, 2, 'To me, boxing is like a ballet, except there''s no music, no choreography, and the dancers hit each other.'),
	(default, 2, 'What is it that makes a complete stranger dive into an icy river to save a solid gold baby? Maybe we''ll never know.'),
	(default, 2, 'We tend to scoff at the beliefs of the ancients. But we can''t scoff at them personally, to their faces, and this is what annoys me.'),
	(default, 2, 'Probably the earliest flyswatters were nothing more than some sort of striking surface attached to the end of a long stick.'),
	(default, 2, 'I think someone should have had the decency to tell me the luncheon was free. To make someone run out with potato salad in his hand, pretending he''s throwing up, is not what I call hospitality.'),
	(default, 2, 'To me, clowns aren''t funny. In fact, they''re kind of scary. I''ve wondered where this started and I think it goes back to the time I went to the circus, and a clown killed my dad.'),
	(default, 2, 'As I bit into the nectarine, it had a crisp juiciness about it that was very pleasurable - until I realized it wasn''t a nectarine at all, but A HUMAN HEAD!!'),
	(default, 2, 'Most people don''t realize that large pieces of coral, which have been painted brown and attached to the skull by common wood screws, can make a child look like a deer.'),
	(default, 2, 'If trees could scream, would we be so cavalier about cutting them down? We might, if they screamed all the time, for no good reason.'),
	(default, 2, 'Better not take a dog on the space shuttle, because if he sticks his head out when you''re coming home his face might burn up.'),
	(default, 2, 'You know what would make a good story? Something about a clown who makes people happy, but inside he''s real sad. Also, he has severe diarrhea.'),
	(default, 2, 'Sometimes when I feel like killing someone, I do a little trick to calm myself down. I''ll go over to the persons house and ring the doorbell. When the person comes to the door, I''m gone, but you know what I''ve left on the porch? A jack-o-lantern with a knife stuck in the side of it''s head with a note that says "You." After that I usually feel a lot better, and no harm done.'),
	(default, 2, 'If you''re a horse, and someone gets on you, and falls off, and then gets right back on you, I think you should buck him off right away.'),
	(default, 2, 'If you ever teach a yodeling class, probably the hardest thing is to keep the students from just trying to yodel right off. You see, we build to that.'),
	(default, 2, 'If you ever fall off the Sears Tower, just go real limp, because maybe you''ll look like a dummy and people will try to catch you because, hey, free dummy.'),
	(default, 2, 'I''d like to see a nude opera, because when they hit those high notes, I bet you can really see it in those genitals.'),
	(default, 2, 'Anytime I see something screech across a room and latch onto someones neck, and the guy screams and tries to get it off, I have to laugh, because what is that thing.'),
	(default, 2, 'He was a cowboy, mister, and he loved the land. He loved it so much he made a woman out of dirt and married her. But when he kissed her, she disintegrated. Later, at the funeral, when the preacher said, "Dust to dust," some people laughed, and the cowboy shot them. At his hanging, he told the others, "I''ll be waiting for you in heaven--with a gun."'),
	(default, 2, 'The memories of my family outings are still a source of strength to me. I remember we''d all pile into the car - I forget what kind it was - and drive and drive. I''m not sure where we''d go, but I think there were some trees there. The smell of something was strong in the air as we played whatever sport we played. I remember a bigger, older guy we called "Dad." We''d eat some stuff, or not, and then I think we went home. I guess some things never leave you.'),
	(default, 2, 'If a kid asks where rain comes from, I think a cute thing to tell him is "God is crying." And if he asks why God is crying, another cute thing to tell him is "Probably because of something you did."'),
	(default, 2, 'Contrary to what most people say, the most dangerous animal in the world is not the lion or the tiger or even the elephant. It''s a shark riding on an elephant''s back, just trampling and eating everything they see.'),
	(default, 2, 'As we were driving, we saw a sign that said "Watch for Rocks." Marta said it should read "Watch for Pretty Rocks." I told her she should write in her suggestion to the highway department, but she started saying it was a joke - just to get out of writing a simple letter! And I thought I was lazy!'),
	(default, 2, 'One thing kids like is to be tricked. For instance, I was going to take my little nephew to DisneyLand, but instead I drove him to an old burned-out warehouse. "Oh, no," I said, "DisneyLand burned down." He cried and cried, but I think that deep down he thought it was a pretty good joke. I started to drive over to the real DisneyLand, but it was getting pretty late.'),
	(default, 2, 'If you saw two guys named Hambone and Flippy, which one would you think liked dolphins the most? I''d say Flippy, wouldn''t you? You''d be wrong, though. It''s Hambone.'),
	(default, 2, 'Laurie got offended that I used the word "puke." But to me, that''s what her dinner tasted like.'),
	(default, 2, 'We used to laugh at Grandpa when he''d head off and go fishing. But we wouldn''t be laughing that evening when he''d come back with some whore he picked up in town.'),
	(default, 2, 'I wish a robot would get elected president. That way, when he came to town, we could all take a shot at him and not feel too bad.'),
	(default, 2, 'As the evening sky faded from a salmon color to a sort of flint gray, I thought back to the salmon I caught that morning, and how gray he was, and how I named him Flint.'),
	(default, 2, 'If you''re a young Mafia gangster out on your first date, I bet it''s real embarrassing if someone tries to kill you.'),
	(default, 2, 'Whenever I see an old lady slip and fall on a wet sidewalk, my first instinct is to laugh. But then I think, what is I was an ant, and she fell on me. Then it wouldn''t seem quite so funny.'),
	(default, 2, 'If you go parachuting, and your parachute doesn''t open, and you friends are all watching you fall, I think a funny gag would be to pretend you were swimming.'),
	(default, 2, 'When I was a kid my favorite relative was Uncle Caveman. After school we''d all go play in his cave, and every once in a while he would eat one of us. It wasn''t until later that I found out that Uncle Caveman was a bear.'),
	(default, 1, 'All of life is a blur of Republicans and meat!'),
	(default, 1, '..Are we having FUN yet...?'),
	(default, 1, 'Life is a POPULARITY CONTEST!  I''m REFRESHINGLY CANDID!!'),
	(default, 1, 'You were s''posed to laugh!'),
	(default, 1, 'Fold, fold, FOLD!!  FOLDING many items!!'),
	(default, 1, 'A can of ASPARAGUS, 73 pigeons, some LIVE ammo, and a FROZEN DAQUIRI!!'),
	(default, 1, 'A dwarf is passing out somewhere in Detroit!'),
	(default, 1, 'A GRAM??  A BRAM...  A GROOM...  A BROOM...  Oh, Yeh!!  Wash the ROOM!!'),
	(default, 1, '...A housewife is wearing a polypyrene jumpsuit!!'),
	(default, 1, 'A shapely CATHOLIC SCHOOLGIRL is FIDGETING inside my costume..'),
	(default, 1, 'A wide-eyed, innocent UNICORN, poised delicately in a MEADOW filled with LILACS, LOLLIPOPS & small CHILDREN at the HUSH of twilight??'),
	(default, 1, 'Actually, what I''d like is a little toy spaceship!!'),
	(default, 1, 'After this, I''m going to BURN some RUBBER!!'),
	(default, 1, 'After THIS, let''s go to PHILADELPHIA and have TRIPLETS!!'),
	(default, 1, 'AIEEEEE!  I am having an UNDULATING EXPERIENCE!'),
	(default, 1, 'ALFRED JARRY!  Say something about th'' DEATH of DISCO!!'),
	(default, 1, 'All I can think of is a platter of organic PRUNE CRISPS being trampled by an army of swarthy, Italian LOUNGE SINGERS...'),
	(default, 1, 'All of a sudden, I want to THROW OVER my promising ACTING CAREER, grow a LONG BLACK BEARD and wear a BASEBALL HAT!! ...  Although I don''t know WHY!!'),
	(default, 1, 'All right, you degenerates!  I want this place evacuated in 20 seconds!'),
	(default, 1, 'All this time I''ve been VIEWING a RUSSIAN MIDGET SODOMIZE a HOUSECAT!'),
	(default, 1, 'Alright, you!!  Imitate a WOUNDED SEAL pleading for a PARKING SPACE!!'),
	(default, 1, 'Am I accompanied by a PARENT or GUARDIAN?'),
	(default, 1, 'Am I elected yet?'),
	(default, 1, '..Am I in a SOAP OPERA??'),
	(default, 1, 'Am I in GRADUATE SCHOOL yet?'),
	(default, 1, 'Am I SHOPLIFTING?'),
	(default, 1, 'America!!  I saw it all!!  Vomiting!  Waving!  JERRY FALWELLING into your void tube of UHF oblivion!!  SAFEWAY of the mind --'),
	(default, 1, 'An air of FRENCH FRIES permeates my nostrils!!'),
	(default, 1, 'An INK-LING?  Sure -- TAKE one!!  Did you BUY any COMMUNIST UNIFORMS??'),
	(default, 1, 'An Italian is COMBING his hair in suburban DES MOINES!'),
	(default, 1, 'And furthermore, my bowling average is unimpeachable!!!'),
	(default, 1, 'ANN JILLIAN''S HAIR makes LONI ANDERSON''S HAIR look like RICARDO MONTALBAN''S HAIR!'),
	(default, 1, 'Are BOTH T.V.S on??'),
	(default, 1, '..  are the STEWED PRUNES still in the HAIR DRYER?'),
	(default, 1, '..Are we having FUN yet...?'),
	(default, 1, 'Are we live or on tape?'),
	(default, 1, 'Are we on STRIKE yet?'),
	(default, 1, 'Are we THERE yet?'),
	(default, 1, 'Are we THERE yet?  My MIND is a SUBMARINE!!'),
	(default, 1, 'Are we THERE yet?!'),
	(default, 1, 'Are we THERE yet??'),
	(default, 1, 'Are you guys lined up for the METHADONE PROGRAM or FOOD STAMPS??'),
	(default, 1, 'Are you mentally here at Pizza Hut??'),
	(default, 1, 'Are you selling NYLON OIL WELLS??  If so, we can use TWO DOZEN!!'),
	(default, 1, 'Are you still an ALCOHOLIC?'),
	(default, 1, 'Are you still SEXUALLY ACTIVE?  Did you BRING th'' REINFORCEMENTS?'),
	(default, 1, 'As a FAD follower, my BEVERAGE choices are rich and fulfilling!'),
	(default, 1, 'As President I have to go vacuum my coin collection!'),
	(default, 1, 'Ask me the DIFFERENCE between PHIL SILVERS and ALEXANDER HAIG!!'),
	(default, 1, 'Awright, which one of you hid my PENIS ENVY?'),
	(default, 1, 'Bagels...'),
	(default, 1, 'BARBARA STANWYCK makes me nervous!!'),
	(default, 1, 'Barbie says, Take quaaludes in gin and go to a disco right away! But Ken says, WOO-WOO!!  No credit at ``Mr. Liquor''''!!'),
	(default, 1, 'BARRY..  That was the most HEART-WARMING rendition of ``I DID IT MY WAY'''' I''ve ever heard!!'),
	(default, 1, 'BEEP-BEEP!!  I''m a ''49 STUDEBAKER!!'),
	(default, 1, 'Being a BALD HERO is almost as FESTIVE as a TATTOOED KNOCKWURST.'),
	(default, 1, 'BELA LUGOSI is my co-pilot..'),
	(default, 1, 'BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-BI-'),
	(default, 1, '...  Blame it on the BOSSA NOVA!!!'),
	(default, 1, '..  bleakness....  desolation....  plastic forks...'),
	(default, 1, 'Bo Derek ruined my life!'),
	(default, 1, 'Boy, am I glad it''s only 1971...'),
	(default, 1, 'Boys, you have ALL been selected to LEAVE th'' PLANET in 15 minutes!!'),
	(default, 1, 'BRYLCREAM is CREAM O'' WHEAT in another DIMENSION..'),
	(default, 1, 'But was he mature enough last night at the lesbian masquerade?'),
	(default, 1, 'By MEER biz doo SCHOIN..'),
	(default, 1, 'C''MON, everybody!!  I''ve flown in LESLIE GORE and two dozen KOSHER BUTCHERS!  They''ll be doing intricate MILITARY MANEUVERS to the soundtrack from "OKLAHOMA"!!'),
	(default, 1, 'CALIFORNIA is where people from IOWA or NEW YORK go to subscribe to CABLE TELEVISION!!'),
	(default, 1, 'Can I have an IMPULSE ITEM instead?'),
	(default, 1, 'Can you MAIL a BEAN CAKE?'),
	(default, 1, 'Catsup and Mustard all over the place!  It''s the Human Hamburger!'),
	(default, 1, 'CHUBBY CHECKER just had a CHICKEN SANDWICH in downtown DULUTH!'),
	(default, 1, 'CHUBBY CHECKER owns my BUILDING!'),
	(default, 1, 'Civilization is fun!  Anyway, it keeps me busy!!'),
	(default, 1, 'Clear the laundromat!!  This whirl-o-matic just had a nuclear meltdown!!'),
	(default, 1, 'Concentrate on th''cute, li''l CARTOON GUYS! Remember the SERIAL NUMBERS!!  Follow the WHIPPLE AVE EXIT!! Have a FREE PEPSI!!  Turn LEFT at th''HOLIDAY INN!! JOIN the CREDIT WORLD!!  MAKE me an OFFER!!!'),
	(default, 1, 'CONGRATULATIONS!  Now should I make thinly veiled comments about DIGNITY, self-esteem and finding TRUE FUN in your RIGHT VENTRICLE??'),
	(default, 1, 'Content:  80% POLYESTER, 20% DACRON..  The waitress''s UNIFORM sheds TARTAR SAUCE like an 8'''' by 10'''' GLOSSY..'),
	(default, 1, 'Could I have a drug overdose?'),
	(default, 1, '"DARK SHADOWS" is on!!  Hey, I think the VAMPIRE forgot his UMBRELLA!!'),
	(default, 1, 'Darling, my ELBOW is FLYING over FRANKFURT, Germany..'),
	(default, 1, 'Dehydrated EGGS are STREWN across ROULETTE TABLES..'),
	(default, 1, 'Did an Italian CRANE OPERATOR just experience uninhibited sensations in a MALIBU HOT TUB?'),
	(default, 1, 'Did I do an INCORRECT THING??'),
	(default, 1, 'Did I say I was a sardine?  Or a bus???'),
	(default, 1, 'Did I SELL OUT yet??'),
	(default, 1, 'Did we bring enough BEEF JERKY?'),
	(default, 1, 'Did YOU find a DIGITAL WATCH in YOUR box of VELVEETA?'),
	(default, 1, 'Did you GAIN WEIGHT in th'' past 5 MINUTES or am I just DREAMING of two BROCCOLI FLORETS lying in an empty GAS TANK?'),
	(default, 1, 'Did you move a lot of KOREAN STEAK KNIVES this trip, Dingy?'),
	(default, 1, 'DIDI...  is that a MARTIAN name, or, are we in ISRAEL?'),
	(default, 1, 'Didn''t I buy a 1951 Packard from you last March in Cairo?'),
	(default, 1, 'Didn''t KIERKEGAARD wear out his TIRES in VIENNA during a SNOWSTORM of FREUD''s unpaid DENTAL BILLS?'),
	(default, 1, 'Disco oil bussing will create a throbbing naugahide pipeline running straight to the tropics from the rug producing regions and devalue the dollar!'),
	(default, 1, 'Dizzy, are we "REAL PEOPLE" or "AMAZING ANIMALS"?'),
	(default, 1, 'Do I have a lifestyle yet?'),
	(default, 1, 'Do I hear th'' SPINNING of various WHIRRING, ROUND, and WARM WHIRLOMATICS?!'),
	(default, 1, 'Do you guys know we just passed thru a BLACK HOLE in space?'),
	(default, 1, 'Do you have exactly what I want in a plaid poindexter bar bat??'),
	(default, 1, '..  Do you like ``TENDER VITTLES?''''?'),
	(default, 1, 'Do you need any MOUTH-TO-MOUTH resuscitation?'),
	(default, 1, 'Do you think the ``Monkees'''' should get gas on odd or even days?'),
	(default, 1, 'Does someone from PEORIA have a SHORTER ATTENTION span than me?'),
	(default, 1, 'Does that mean I''m not a well-adjusted person??'),
	(default, 1, '..  does your DRESSING ROOM have enough ASPARAGUS?'),
	(default, 1, 'DON''T go!!  I''m not HOWARD COSELL!!  I know POLISH JOKES...  WAIT!! Don''t go!!  I AM Howard Cosell!...  And I DON''T know Polish jokes!!'),
	(default, 1, 'Don''t hit me!!  I''m in the Twilight Zone!!!'),
	(default, 1, 'Don''t SANFORIZE me!!'),
	(default, 1, 'Don''t worry, nobody really LISTENS to lectures in MOSCOW, either! ..  FRENCH, HISTORY, ADVANCED CALCULUS, COMPUTER PROGRAMMING, BLACK STUDIES, SOCIOBIOLOGY!..  Are there any QUESTIONS??'),
	(default, 1, 'Edwin Meese made me wear CORDOVANS!!'),
	(default, 1, 'Eisenhower!!  Your mimeograph machine upsets my stomach!!'),
	(default, 1, 'Either CONFESS now or we go to ``PEOPLE''S COURT''''!!'),
	(default, 1, 'Everybody gets free BORSCHT!'),
	(default, 1, 'Everybody is going somewhere!!  It''s probably a garage sale or a disaster Movie!!'),
	(default, 1, '..Everything is....FLIPPING AROUND!!'),
	(default, 1, 'Everything will be ALL RIGHT if we can just remember things about ALGEBRA.. or SOCCER..  or SOCIALISM..'),
	(default, 1, 'Everywhere I look I see NEGATIVITY and ASPHALT...'),
	(default, 1, 'Excuse me, but didn''t I tell you there''s NO HOPE for the  survival of OFFSET PRINTING?'),
	(default, 1, 'FEELINGS are cascading over me!!!'),
	(default, 1, 'Feel th'' WHIRLING BUFFERS buffing away all that stress...  Years of ROAD TAR gently washing away...'),
	(default, 1, 'Finally, Zippy drives his 1958 RAMBLER METROPOLITAN into the  faculty dining room.'),
	(default, 1, 'FIRST, I was in a TRUCK...THEN, I was in a DINER...'),
	(default, 1, 'FIRST, I''m covering you with OLIVE OIL and PRUNE WHIP!!'),
	(default, 1, 'First, I''m going to give you all the ANSWERS to today''s test..  So just plug in your SONY WALKMANS and relax!!'),
	(default, 1, 'FISH-NET-FISH-NET-FISH-NET-FISH-NET-FISH!!'),
	(default, 1, 'FOOLED you!  Absorb EGO SHATTERING impulse rays, polyester poltroon!!'),
	(default, 1, 'Four thousand different MAGNATES, MOGULS & NABOBS are romping in my  gothic solarium!!'),
	(default, 1, 'FROZEN ENTREES may be flung by members of opposing SWANSON SECTS..'),
	(default, 1, 'FUN is never having to say you''re SUSHI!!'),
	(default, 1, 'Gee, I feel kind of LIGHT in the head now, knowing I can''t make  my satellite dish PAYMENTS!'),
	(default, 1, '...Get me a GIN and TONIC!!...make it HAIR TONIC!!'),
	(default, 1, 'Gibble, Gobble, we ACCEPT YOU ---'),
	(default, 1, 'Give them RADAR-GUIDED SKEE-BALL LANES and VELVEETA BURRITOS!!'),
	(default, 1, 'Go on, EMOTE!  I was RAISED on thought balloons!!'),
	(default, 1, 'GOOD-NIGHT, everybody..  Now I have to go administer FIRST-AID  to my pet LEISURE SUIT!!'),
	(default, 1, 'Ha ha   Ha ha  Ha ha   Ha  Ha  Ha  Ha  -- When will I EVER stop HAVING  FUN?!!'),
	(default, 1, 'HAIR TONICS, please!!'),
	(default, 1, 'Half a mind is a terrible thing to waste!'),
	(default, 1, 'Hand me a pair of leather pants and a CASIO keyboard  -- I''m living for today!'),
	(default, 1, 'Has everybody got HALVAH spread all over their ANKLES??...  Now, it''s time to ``HAVE A NAGEELA''''!!'),
	(default, 1, 'Have my two-tone, 1958 Nash METRO brought around..'),
	(default, 1, '..  he dominates the DECADENT SUBWAY SCENE.'),
	(default, 1, 'He is the MELBA-BEING...  the ANGEL CAKE...   XEROX him...  XEROX him --'),
	(default, 1, 'He probably just wants to take over my CELLS and then EXPLODE  inside me like a BARREL of runny CHOPPED LIVER!  Or maybe he''d  like to PSYCHOLOGICALLY TERRORIZE ME until I have no objection  to a RIGHT-WING MILITARY TAKEOVER of my apartment!!  I guess  I should call AL PACINO!'),
	(default, 1, 'HELLO KITTY gang terrorizes town, family STICKERED to death!'),
	(default, 1, 'HELLO, everybody, I''m a HUMAN!!'),
	(default, 1, 'Hello, GORRY-O!!  I''m a GENIUS from HARVARD!!'),
	(default, 1, 'HELLO, little boys!   Gimme a MINT TULIP!!  Let''s do the BOSSA NOVA!!'),
	(default, 1, '--Hello, POLICE?  I"ve got ABBOTT & COSTELLO here on suspicion of  HIGHWAY ROBBERY!!'),
	(default, 1, 'Hello.  I know the divorce rate among unmarried Catholic  Alaskan females!!'),
	(default, 1, 'Hello.  Just walk along and try NOT to think about your  INTESTINES being almost FORTY YARDS LONG!!'),
	(default, 1, 'Hello...  IRON CURTAIN?  Send over a SAUSAGE PIZZA!  World War III?  No thanks!'),
	(default, 1, 'Hello?  Enema Bondage?  I''m calling because I want to be happy, I guess..'),
	(default, 1, 'Here I am at the flea market but nobody is buying  my urine sample bottles..'),
	(default, 1, '..  here I am in 53 B.C. and all I want is a dill pickle!!'),
	(default, 1, 'Here I am in the POSTERIOR OLFACTORY LOBULE but I don''t see CARL SAGAN  anywhere!!'),
	(default, 1, 'Here is my refrigerator full of FLANK STEAK...and over there is my  UPHOLSTERED CANOE...I don''t know WHY I OWN them!!'),
	(default, 1, 'Here we are in America...  when do we collect unemployment?'),
	(default, 1, 'HERE!!  Put THIS on!!  I''m in CHARGE!!'),
	(default, 1, 'Hey!!  Let''s watch the'' ELEVATOR go UP and DOWN at th'' HILTON HOTEL!!'),
	(default, 1, 'Hey, I LIKE that POINT!!'),
	(default, 1, 'Hey, LOOK!!  A pair of SIZE 9 CAPRI PANTS!!  They probably belong to  SAMMY DAVIS, JR.!!'),
	(default, 1, 'Hey, wait a minute!!  I want a divorce!!..  you''re not Clint Eastwood!!'),
	(default, 1, 'Hey, waiter!  I want a NEW SHIRT and a PONY TAIL with lemon sauce!'),
	(default, 1, 'Hiccuping & trembling into the WASTE DUMPS of New Jersey like some  drunken CABBAGE PATCH DOLL, coughing in line at FIORUCCI''S!!'),
	(default, 1, 'Hmmm..  a CRIPPLED ACCOUNTANT with a FALAFEL sandwich is HIT  by a TROLLEY-CAR..'),
	(default, 1, 'Hmmm..  A hash-singer and a cross-eyed guy were SLEEPING on a deserted  island, when...'),
	(default, 1, 'Hmmm...  a PINHEAD, during an EARTHQUAKE, encounters an ALL-MIDGET FIDDLE  ORCHESTRA...  ha..  ha..'),
	(default, 1, 'Hmmm...  an arrogant bouquet with a subtle suggestion of  POLYVINYL CHLORIDE...'),
	(default, 1, '..Hmmm...This thing is really VIBRATING! ..It''s getting WARM, too!'),
	(default, 1, 'Hold the MAYO & pass the COSMIC AWARENESS...'),
	(default, 1, 'HOORAY, Ronald!!  Now YOU can marry LINDA RONSTADT too!!'),
	(default, 1, 'HOW could a GLASS be YELLING??'),
	(default, 1, 'How do I get HOME?'),
	(default, 1, 'How do you explain Wayne Newton''s POWER over millions?  It''s th'' MOUSTACHE...  Have you ever noticed th'' way it radiates  SINCERITY, HONESTY & WARMTH?  It''s a MOUSTACHE you want to take  HOME and introduce to NANCY SINATRA!'),
	(default, 1, 'How many retired bricklayers from FLORIDA are out purchasing  PENCIL SHARPENERS right NOW??'),
	(default, 1, 'How''s it going in those MODULAR LOVE UNITS??'),
	(default, 1, 'How''s the wife?  Is she at home enjoying capitalism?'),
	(default, 1, '..  hubub, hubub, HUBUB, hubub, hubub, hubub, HUBUB, hubub, hubub, hubub.'),
	(default, 1, 'HUGH BEAUMONT died in 1982!!'),
	(default, 1, 'HUMAN REPLICAS are inserted into VATS of NUTRITIONAL YEAST...'),
	(default, 1, 'Hydraulic pizza oven!!  Guided missile!  Herring sandwich!  Styrofoam!  Jayne Mansfield!  Aluminum siding!  Borax!  Pedal pushers!  Jukebox!'),
	(default, 1, 'I always have fun because I''m out of my mind!!!'),
	(default, 1, 'I always liked FLAG DAY!!'),
	(default, 1, 'I always wanted a NOSE JOB!!'),
	(default, 1, 'I am a jelly donut.  I am a jelly donut.'),
	(default, 1, 'I am a traffic light, and Alan Ginsberg kidnapped my laundry in 1927!'),
	(default, 1, 'I am covered with pure vegetable oil and I am writing a best seller!'),
	(default, 1, 'I am deeply CONCERNED and I want something GOOD for BREAKFAST!'),
	(default, 1, 'I am having a CONCEPTION--'),
	(default, 1, 'I am having a pleasant time!!'),
	(default, 1, 'I am having FUN...  I wonder if it''s NET FUN or GROSS FUN?'),
	(default, 1, 'I am KING BOMBA of Sicily!..I will marry LUCILLE BALL next Friday!'),
	(default, 1, 'I am NOT a nut....'),
	(default, 1, 'I appoint you ambassador to Fantasy Island!!!'),
	(default, 1, 'I brought my BOWLING BALL - and some DRUGS!!'),
	(default, 1, 'I call it a "SARDINE ON WHEAT"!'),
	(default, 1, '-- I can do ANYTHING ... I can even ... SHOPLIFT!!'),
	(default, 1, 'I can see you GUYS an'' GALS need a LOT of HELP...You''re all very  STUPID!!  I used to be STUPID, too..before I started watching UHF-TV!!'),
	(default, 1, 'I can''t decide which WRONG TURN to make first!!  I wonder if BOB GUCCIONE has these problems!'),
	(default, 1, 'I can''t think about that.  It doesn''t go with HEDGES in the shape of  LITTLE LULU -- or ROBOTS making BRICKS...'),
	(default, 1, 'I decided to be JOHN TRAVOLTA instead!!'),
	(default, 1, 'I demand IMPUNITY!'),
	(default, 1, 'I didn''t order any WOO-WOO...  Maybe a YUBBA..  But no WOO-WOO!'),
	(default, 1, 'I don''t believe there really IS a GAS SHORTAGE..  I think it''s all  just a BIG HOAX on the part of the plastic sign salesmen--  ..  to sell more numbers!!'),
	(default, 1, '..  I don''t know why but, suddenly, I want to discuss declining I.Q.  LEVELS with a blue ribbon SENATE SUB-COMMITTEE!'),
	(default, 1, 'I don''t know WHY I said that..  I think it came from the FILLINGS  in my rear molars..'),
	(default, 1, 'I don''t think you fellows would do so much RAPING and PILLAGING if you  played more PINBALL and watched CABLE TELEVISION!!'),
	(default, 1, '..  I don''t understand the HUMOR of the THREE STOOGES!!'),
	(default, 1, 'I feel better about world problems now!'),
	(default, 1, 'I feel like a wet parking meter on Darvon!'),
	(default, 1, 'I feel like I am sharing a ``CORN-DOG'''' with NIKITA KHRUSCHEV..'),
	(default, 1, 'I feel like I''m in a Toilet Bowl with a thumbtack in my forehead!!'),
	(default, 1, 'I feel partially hydrogenated!'),
	(default, 1, 'I feel real SOPHISTICATED being in FRANCE!'),
	(default, 1, '..  I feel..  JUGULAR..'),
	(default, 1, 'I fill MY industrial waste containers with old copies  of the ``WATCHTOWER'''' and then add HAWAIIAN PUNCH to  the top..  They look NICE in the yard--'),
	(default, 1, 'I FORGOT to do the DISHES!!'),
	(default, 1, 'I guess it was all a DREAM..  or an episode of HAWAII FIVE-O...'),
	(default, 1, 'I guess we can live on his POT FARM in HADES!!'),
	(default, 1, 'I guess you guys got BIG MUSCLES from doing too much STUDYING!'),
	(default, 1, 'I had a lease on an OEDIPUS COMPLEX back in ''81...'),
	(default, 1, 'I had pancake makeup for brunch!'),
	(default, 1, 'I have a TINY BOWL in my HEAD'),
	(default, 1, 'I HAVE a towel.'),
	(default, 1, 'I have a very good DENTAL PLAN.  Thank you.'),
	(default, 1, '..  I have a VISION!  It''s a RANCID double-FISHWICH on an ENRICHED BUN!!'),
	(default, 1, 'I have accepted Provolone into my life!'),
	(default, 1, 'I have many CHARTS and DIAGRAMS..'),
	(default, 1, 'I have no actual hairline...'),
	(default, 1, 'I have nostalgia for the late Sixties!  In 1969 I left my laundry with  a hippie!!  During an unauthorized Tupperware party it was chopped &  diced!'),
	(default, 1, '--- I have seen the FUN ---'),
	(default, 1, 'I have seen these EGG EXTENDERS in my Supermarket..  ..  I have read the INSTRUCTIONS...'),
	(default, 1, 'I have the power to HALT PRODUCTION on all TEENAGE SEX COMEDIES!!'),
	(default, 1, 'I HAVE to buy a new ``DODGE MISER'''' and two dozen JORDACHE  JEANS because my viewscreen is ``USER-FRIENDLY''''!!'),
	(default, 1, 'I haven''t been married in over six years, but we had sexual counseling  every day from Oral Roberts!!'),
	(default, 1, 'I HIJACKED a 747 to get here!!  I hope those fabulous CONEHEADS are at HOME!!'),
	(default, 1, 'I hope I bought the right relish...  zzzzzzzzz...'),
	(default, 1, 'I hope something GOOD came in the mail today so I have  a REASON to live!!'),
	(default, 1, 'I hope the ``Eurythmics'''' practice birth control...'),
	(default, 1, 'I hope you millionaires are having fun!  I just invested half  your life savings in yeast!!'),
	(default, 1, 'I invented skydiving in 1989!'),
	(default, 1, 'I joined scientology at a garage sale!!'),
	(default, 1, 'I just bought FLATBUSH from MICKEY MANTLE!'),
	(default, 1, 'I just forgot my whole philosophy of life!!!'),
	(default, 1, 'I just got my PRINCE bumper sticker..  But now I can''t remember WHO he is...'),
	(default, 1, 'I just had a MAJOR CONTRACT DISPUTE with SUZANNE SOMERS!!'),
	(default, 1, 'I just had a NOSE JOB!!'),
	(default, 1, 'I just had my entire INTESTINAL TRACT coated with TEFLON!'),
	(default, 1, 'I just heard the SEVENTIES were over!!  And I was just getting in touch  with my LEISURE SUIT!!'),
	(default, 1, 'I just put lots of the EGG SALAD in the SILK SOCKS --'),
	(default, 1, 'I just remembered something about a TOAD!'),
	(default, 1, '..I just walked into th'' HOUSE OF REPRESENTATIVES with fourteen WET  DOLPHINS and an out-of-date MARRIAGE MANUAL...'),
	(default, 1, 'A KAISER ROLL?!  What good is a Kaiser Roll without a little  COLE SLAW on the SIDE?'),
	(default, 1, 'I Know A Joke'),
	(default, 1, 'I know how to do SPECIAL EFFECTS!!'),
	(default, 1, 'I know how to get the hostesses released!  Give them their own  television series!'),
	(default, 1, 'I know th''MAMBO!!  I have a TWO-TONE CHEMISTRY SET!!'),
	(default, 1, 'I know things about TROY DONAHUE that can''t even be PRINTED!!'),
	(default, 1, 'I left my WALLET in the BATHROOM!!'),
	(default, 1, 'I LIKE Aisle 7a.'),
	(default, 1, 'I like the IMPUDENT NOSE on that car..  Are you a TEEN-AGER?  '),
	(default, 1, 'I like the way ONLY their mouths move..  They look like DYING OYSTERS'),
	(default, 1, 'I like your SNOOPY POSTER!!'),
	(default, 1, '... I live in a FUR-LINE FALLOUT SHELTER'),
	(default, 1, 'I love FRUIT PICKERS!!'),
	(default, 1, '--``I love KATRINKA because she drives a PONTIAC.  We''re going away now.  I fed the cat. - Zippy'''''),
	(default, 1, 'I LOVE juxtaposing th'' splendor of an unpopulated ARROYO with  th'' SLEEK lines of ``NARCISSUS-X'''', my new SPORTS UTILITY VEHICLE!'),
	(default, 1, 'I love ROCK ''N ROLL!  I memorized the all WORDS to ``WIPE-OUT'''' in 1965!!'),
	(default, 1, '..I must be a VETERINARIAN..'),
	(default, 1, 'I need "RONDO".'),
	(default, 1, 'I need to discuss BUY-BACK PROVISIONS with at least  six studio SLEAZEBALLS!!'),
	(default, 1, 'I once decorated my apartment entirely in ten foot salad forks!!'),
	(default, 1, 'I own seven-eighths of all the artists in downtown Burbank!'),
	(default, 1, 'I OWN six pink HIPPOS!!'),
	(default, 1, 'I predict that by 1993 everyone will live in and around LAS VEGAS and  wear BEATLE HAIRCUTS!'),
	(default, 1, 'I pretend I''m living in a styrofoam packing crate, high in th''  SWISS ALPS, still unable to accept th'' idea of TOUCH-TONE DIALING!!'),
	(default, 1, 'I put aside my copy of ``BOWLING WORLD'''' and think  about GUN CONTROL legislation..'),
	(default, 1, 'I represent a sardine!!'),
	(default, 1, 'I request a weekend in Havana with Phil Silvers!'),
	(default, 1, '..  I see TOILET SEATS...'),
	(default, 1, 'I selected E5...  but I didn''t hear ``Sam the Sham and the Pharaohs''''!'),
	(default, 1, 'I smell a RANCID CORN DOG!'),
	(default, 1, 'I smell like a wet reducing clinic on Columbus Day!'),
	(default, 1, 'I think I am an overnight sensation right now!!'),
	(default, 1, '..  I think I''d better go back to my DESK and toy with  a few common MISAPPREHENSIONS...'),
	(default, 1, 'I think I''ll do BOTH if I can get RESIDUALS!!'),
	(default, 1, '..  I think I''ll KILL myself by leaping out of this  14th STORY WINDOW while reading ERICA JONG''S poetry!!'),
	(default, 1, 'I think I''ll make SCRAMBLED EGGS!!  They''re each in LITTLE SHELLS..'),
	(default, 1, '...I think I''m having an overnight sensation right now!!'),
	(default, 1, 'I think my CAREER is RUINED!!'),
	(default, 1, 'I used to be a FUNDAMENTALIST, but then I heard about the  HIGH RADIATION LEVELS and bought an ENCYCLOPEDIA!!'),
	(default, 1, '..  I want a COLOR T.V. and a VIBRATING BED!!!'),
	(default, 1, 'I want a VEGETARIAN BURRITO to go..  with EXTRA MSG!!'),
	(default, 1, 'I want a WESSON OIL lease!!'),
	(default, 1, 'I want another RE-WRITE on my CAESAR SALAD!!'),
	(default, 1, 'I want DUSTIN HOFFMAN!! .. I want LIBERACE!!  YOW!!'),
	(default, 1, 'I want EARS!  I want two ROUND BLACK EARS to make me feel warm ''n secure!!'),
	(default, 1, '..  I want FORTY-TWO TRYNEL FLOATATION SYSTEMS installed within  SIX AND A HALF HOURS!!!'),
	(default, 1, 'I want the presidency so bad I can already taste the hors d''oeuvres.'),
	(default, 1, 'I want to dress you up as TALLULAH BANKHEAD and cover you with  VASELINE and WHEAT THINS..'),
	(default, 1, 'I want to kill everyone here with a cute colorful Hydrogen Bomb!!'),
	(default, 1, '..  I want to perform cranial activities with Tuesday Weld!!'),
	(default, 1, 'I want to read my new poem about pork brains and outer space...'),
	(default, 1, 'I want to so HAPPY, the VEINS in my neck STAND OUT!!'),
	(default, 1, 'I want to TAKE IT HOME and DRESS IT UP in HOT PANTS!!'),
	(default, 1, 'I want you to MEMORIZE the collected poems of EDNA ST VINCENT MILLAY..  BACKWARDS!!'),
	(default, 1, 'I want you to organize my PASTRY trays...  my TEA-TINS are gleaming in  formation like a ROW of DRUM MAJORETTES --  please don''t be FURIOUS with me --'),
	(default, 1, 'I was born in a Hostess Cupcake factory before the sexual revolution!'),
	(default, 1, 'I was giving HAIR CUTS to th'' SAUCER PEOPLE ..  I''m CLEAN!!'),
	(default, 1, 'I was in a HOT TUB!  I was NORMAL!  I was ITALIAN!!  I enjoyed th''  EARTHQUAKE!'),
	(default, 1, 'I was in EXCRUCIATING PAIN until I started reading JACK AND JILL  Magazine!!'),
	(default, 1, 'I was making donuts and now I''m on a bus!'),
	(default, 1, 'I will establish the first SHOPPING MALL in NUTLEY, New Jersey...'),
	(default, 1, 'I will invent "TIDY BOWL"...'),
	(default, 1, 'I will SHAVE and buy JELL-O and bring my MARRIAGE MANUAL!!'),
	(default, 1, 'I wish I was a sex-starved manicurist found dead in the Bronx!!'),
	(default, 1, 'I wish I was on a Cincinnati street corner holding a clean dog!'),
	(default, 1, 'I wonder if I could ever get started in the credit world?'),
	(default, 1, '..  I wonder if I ought to tell them about my PREVIOUS LIFE  as a COMPLETE STRANGER?'),
	(default, 1, 'I wonder if I should put myself in ESCROW!!'),
	(default, 1, 'I wonder if there''s anything GOOD on tonight?'),
	(default, 1, 'I would like to urinate in an OVULAR, porcelain pool --'),
	(default, 1, 'I''d like MY data-base JULIENNED and stir-fried!'),
	(default, 1, 'I''d like some JUNK FOOD...  and then I want to be ALONE --'),
	(default, 1, 'I''d like TRAINED SEALS and a CONVERTIBLE on my doorstep by NOON!!'),
	(default, 1, 'I''ll clean your ROOM!!  I know some GOOD stories, too!!  All about  ROAD Island''s, HUSH Puppies, and how LUKE finds GOLD on his LAND!!'),
	(default, 1, 'I''ll eat ANYTHING that''s BRIGHT BLUE!!'),
	(default, 1, 'I''LL get it!!  It''s probably a FEW of my ITALIAN GIRL-FRIENDS!!'),
	(default, 1, '..I''ll make you an ASHTRAY!!'),
	(default, 1, 'I''ll show you MY telex number if you show me YOURS...'),
	(default, 1, 'I''ll take ROAST BEEF if you''re out of LAMB!!'),
	(default, 1, 'I''m a fuschia bowling ball somewhere in Brittany'),
	(default, 1, 'I''m a GENIUS!  I want to dispute sentence structure with SUSAN SONTAG!!'),
	(default, 1, 'I''m a nuclear submarine under the polar ice cap and I need a Kleenex!'),
	(default, 1, 'I''m also against BODY-SURFING!!'),
	(default, 1, 'I''m also pre-POURED pre-MEDITATED and pre-RAPHAELITE!!'),
	(default, 1, 'I''m an East Side TYPE..'),
	(default, 1, 'I''m ANN LANDERS!!  I can SHOPLIFT!!'),
	(default, 1, 'I''m changing the CHANNEL..  But all I get is commercials  for ``RONCO MIRACLE BAMBOO STEAMERS''''!'),
	(default, 1, 'I''m continually AMAZED at th''breathtaking effects of WIND EROSION!!'),
	(default, 1, 'I''m CONTROLLED by the CIA!!  EVERYONE is controlled by the CIA!!'),
	(default, 1, 'I''m definitely not in Omaha!'),
	(default, 1, 'I''m DESPONDENT...  I hope there''s something DEEP-FRIED under this  miniature DOMED STADIUM...'),
	(default, 1, 'I''m dressing up in an ill-fitting IVY-LEAGUE SUIT!!  Too late...'),
	(default, 1, 'I''m EMOTIONAL now because I have MERCHANDISING CLOUT!!'),
	(default, 1, 'I''m encased in the lining of a pure pork sausage!!'),
	(default, 1, 'I''m EXCITED!!  I want a FLANK STEAK WEEK-END!!  I think I''m JULIA  CHILD!!'),
	(default, 1, 'I''m GLAD I remembered to XEROX all my UNDERSHIRTS!!'),
	(default, 1, 'I''m gliding over a NUCLEAR WASTE DUMP near ATLANTA, Georgia!!'),
	(default, 1, 'I''m having a BIG BANG THEORY!!'),
	(default, 1, 'I''m having a MID-WEEK CRISIS!'),
	(default, 1, 'I''m having a RELIGIOUS EXPERIENCE..  and I don''t take any DRUGS'),
	(default, 1, 'I''m having a tax-deductible experience!  I need an energy crunch!!'),
	(default, 1, 'I''m having an emotional outburst!!'),
	(default, 1, 'I''m having an EMOTIONAL OUTBURST!!  But, uh, WHY is there a WAFFLE  in my PAJAMA POCKET??'),
	(default, 1, 'I''m having BEAUTIFUL THOUGHTS about the INSIPID WIVES  of smug and wealthy CORPORATE LAWYERS..'),
	(default, 1, 'I''m having fun HITCHHIKING to CINCINNATI or FAR ROCKAWAY!!'),
	(default, 1, '..  I''m IMAGINING a sensuous GIRAFFE, CAVORTING in the BACK ROOM  of a KOSHER DELI --'),
	(default, 1, 'I''m in a twist contest!!  I''m in a bathtub!  It''s on Mars!!  I''m in  tip-top condition!'),
	(default, 1, 'I''m in ATLANTIC CITY riding in a comfortable ROLLING CHAIR...'),
	(default, 1, 'I''m in direct contact with many advanced fun CONCEPTS.'),
	(default, 1, 'I''m in DISGUISE as a BAGGAGE CHECKER....I can watch the house, if it''s  ORANGE...'),
	(default, 1, 'I''m in LOVE with DON KNOTTS!!'),
	(default, 1, 'I''m into SOFTWARE!'),
	(default, 1, 'I''m losing my hair..did it go to ATLANTIC CITY??'),
	(default, 1, 'I''m meditating on the FORMALDEHYDE and the ASBESTOS leaking into my  PERSONAL SPACE!!'),
	(default, 1, 'I''m MENTALLY here..  but PHYSICALLY I''m purchasing NAUGAHYDE furniture  in the'' SUBURBS of PHOENIX!!'),
	(default, 1, 'I''m mentally OVERDRAWN!  What''s that SIGNPOST up ahead?  Where''s ROD STERLING when you really need him?'),
	(default, 1, 'I''m not an Iranian!!  I voted for Dianne Feinstein!!'),
	(default, 1, 'I''m not available for comment..'),
	(default, 1, 'I''m pretending I''m pulling in a TROUT!  Am I doing it correctly??'),
	(default, 1, 'I''m pretending that we''re all watching PHIL SILVERS  instead of RICARDO MONTALBAN!'),
	(default, 1, 'I''m protected by a ROLL-ON I rented from AVIS..'),
	(default, 1, 'I''m QUIETLY reading the latest issue of ``BOWLING WORLD''''  while my wife and two children stand QUIETLY BY..'),
	(default, 1, 'I''m rated PG-34!!'),
	(default, 1, 'I''m receiving a coded message from EUBIE BLAKE!!'),
	(default, 1, 'I''m RELIGIOUS!!  I love a man with a HAIRPIECE!!  Equip me with MISSILES!!'),
	(default, 1, 'I''m reporting for duty as a modern person.  I want to do  the Latin Hustle now!'),
	(default, 1, 'I''m shaving!!  I''M SHAVING!!'),
	(default, 1, 'I''m sitting on my SPEED QUEEN..  To me, it''s ENJOYABLE..  I''m WARM..  I''m VIBRATORY..'),
	(default, 1, 'I''m thinking about DIGITAL READ-OUT systems and  computer-generated IMAGE FORMATIONS..'),
	(default, 1, 'I''m totally DESPONDENT over the LIBYAN situation and the price of CHICKEN..'),
	(default, 1, 'I''m using my X-RAY VISION to obtain a rare glimpse of the  INNER WORKINGS of this POTATO!!'),
	(default, 1, 'I''m wearing PAMPERS!!'),
	(default, 1, 'I''m wet!  I''m wild!'),
	(default, 1, 'I''m working under the direct orders of WAYNE NEWTON to deport  consenting adults!'),
	(default, 1, 'I''m young..  I''m HEALTHY..  I can HIKE THRU CAPT GROGAN''S LUMBAR REGIONS!'),
	(default, 1, 'I''m ZIPPY the PINHEAD and I''m totally committed to the festive mode.'),
	(default, 1, 'I''m ZIPPY!!  Are we having FUN yet??'),
	(default, 1, 'I''ve been WRITING to SOPHIA LOREN every 45 MINUTES since JANUARY 1ST!!'),
	(default, 1, 'I''ve got a COUSIN who works in the GARMENT DISTRICT...'),
	(default, 1, 'I''ve got an IDEA!!  Why don''t I STARE at you so HARD, you forget your SOCIAL SECURITY NUMBER!!'),
	(default, 1, 'I''ve got to get these SNACK CAKES to NEWARK by DAWN!!'),
	(default, 1, 'I''ve gotta GO, now!!  I wanta tell you you''re a GREAT bunch of guys  but you ought to CHANGE your UNDERWEAR more often!!'),
	(default, 1, 'I''ve read SEVEN MILLION books!!'),
	(default, 1, '..  ich bin in einem dusenjet ins jahr 53 vor chr...  ich lande im antiken Rom...  einige gladiatoren spielen scrabble...  ich rieche PIZZA...'),
	(default, 1, 'If a person is FAMOUS in this country, they have to go on the ROAD  for MONTHS at a time and have their name misspelled on the SIDE  of a GREYHOUND SCENICRUISER!!'),
	(default, 1, 'If elected, Zippy pledges to each and every American  a 55-year-old houseboy...'),
	(default, 1, 'If I am elected no one will ever have to do their laundry again!'),
	(default, 1, 'If I am elected, the concrete barriers around the WHITE HOUSE  will be replaced by tasteful foam replicas of ANN MARGARET!'),
	(default, 1, '.. If I cover this entire WALL with MAZOLA, who I have to give my  AGENT ten per cent??'),
	(default, 1, 'If I felt any more SOPHISTICATED I would DIE of EMBARRASSMENT!'),
	(default, 1, 'If I had a Q-TIP, I could prevent th''collapse of NEGOTIATIONS!!'),
	(default, 1, '..  If I had heart failure right now, I couldn''t be a more fortunate man!!'),
	(default, 1, 'If I have enough money to buy 5,000 CANS of NOODLE-RONI, can I get a  VAT of MARSHMALLOW FLUFF free??'),
	(default, 1, 'If I pull this SWITCH I''ll be RITA HAYWORTH!!  Or a SCIENTOLOGIST!'),
	(default, 1, '- if it GLISTENS, gobble it!!'),
	(default, 1, 'If our behavior is strict, we do not need fun!'),
	(default, 1, 'If Robert Di Niro assassinates Walter Slezak, will  Jodie Foster marry Bonzo??'),
	(default, 1, 'If this is the DATING GAME I want to know your FAVORITE PLANET!  Do I  get th'' MICROWAVE MOPED?'),
	(default, 1, 'If this was a SWEDISH MOVIE, I''d take off your GO-GO BOOTS!!'),
	(default, 1, 'If you STAY in China, I''ll give you 4,000 BUSHELS of "ATOMIC MOUSE"  pencil sharpeners!!'),
	(default, 1, 'Imagine--a WORLD without POODLES...'),
	(default, 1, 'Impudent..  Yet possessing a certain ALUMINUM SILICATE  overbite....Needs REDDY-WHIP!!'),
	(default, 1, '-- In 1962, you could buy a pair of SHARKSKIN SLACKS, with a  ``Continental Belt,'''' for $10.99!!'),
	(default, 1, 'In Newark the laundromats are open 24 hours a day!'),
	(default, 1, 'In order to make PLANS for the WEEKEND...so that we can read RESTAURANT  REVIEWS and decide to GO to that restaurant & then NEVER GO...so we can  meet a FRIEND after work in a BAR and COMPLAIN about Interior Sect''y  JAMES WATT until the SUBJECT is changed to NUCLEAR BLACKMAIL...and so  our RELATIVES can FORCE us to listen to HOCKEY STATISTICS while we  wait for them to LEAVE on the 7:48....'),
	(default, 1, 'INSIDE, I have the same personality disorder as LUCY RICARDO!!'),
	(default, 1, 'Inside, I''m already SOBBING!'),
	(default, 1, 'Intra-mural sports results are filtering through th'' plumbing...'),
	(default, 1, 'Is a tattoo real, like a curb or a battleship?  Or are we suffering in Safeway?'),
	(default, 1, 'Is it 1974?  What''s for SUPPER?  Can I spend my COLLEGE FUND in  one wild afternoon??'),
	(default, 1, 'Is it clean in other dimensions?'),
	(default, 1, 'Is it FUN to be a MIDGET?'),
	(default, 1, 'Is it NOUVELLE CUISINE when 3 olives are struggling with a scallop  in a plate of SAUCE MORNAY?'),
	(default, 1, 'Is something VIOLENT going to happen to a GARBAGE CAN?'),
	(default, 1, 'Is the EIGHTIES when they had ART DECO and GERALD McBOING-BOING lunch  boxes??'),
	(default, 1, 'Is there something I should be DOING with a GLAZED DONUT??'),
	(default, 1, 'Is this "BIKINI BEACH"?'),
	(default, 1, 'Is this "BOOZE"?'),
	(default, 1, 'Is this an out-take from the ``BRADY BUNCH''''?'),
	(default, 1, 'Is this ANYWHERE, USA?'),
	(default, 1, 'Is this BOISE??'),
	(default, 1, 'Is this going to involve RAW human ecstasy?'),
	(default, 1, 'Is this my STOP??'),
	(default, 1, 'Is this TERMINAL fun?'),
	(default, 1, 'Is this the line for the latest whimsical YUGOSLAVIAN drama which also  makes you want to CRY and reconsider the VIETNAM WAR?'),
	(default, 1, 'Is this where people are HOT and NICE and they give you TOAST for  FREE??'),
	(default, 1, 'Isn''t this my STOP?!'),
	(default, 1, 'It don''t mean a THING if you ain''t got that SWING!!'),
	(default, 1, 'It was a JOKE!!  Get it??  I was receiving messages  from DAVID LETTERMAN!!  YOW!!'),
	(default, 1, 'It''s 74 degrees, 12 minutes NORTH, and 41 degrees, 3 minutes EAST!!  Soon, it will be TUESDAY!!'),
	(default, 1, 'It''s a lot of fun being alive...  I wonder if my bed is made?!?'),
	(default, 1, 'It''s hard being an ARTIST!!'),
	(default, 1, 'It''s NO USE..  I''ve gone to ``CLUB MED''''!!'),
	(default, 1, 'It''s OBVIOUS..  The FURS never reached ISTANBUL..  You were  an EXTRA in the REMAKE of ``TOPKAPI''''..  Go home to your  WIFE..  She''s making FRENCH TOAST!'),
	(default, 1, 'It''s OKAY --- I''m an INTELLECTUAL, too.'),
	(default, 1, '...It''s REAL ROUND..  And it''s got a POINTY PART right in the MIDDLE!!  The shape is SMOOTH..  ..And COLD.. It feels very COMFORTABLE on my  CHEEK..  I''m getting EMOTIONAL..'),
	(default, 1, 'It''s so OBVIOUS!!'),
	(default, 1, 'It''s strange, but I''m only TRULY ALIVE when I''m covered in POLKA DOTS  and TACO SAUCE...'),
	(default, 1, 'It''s the land of DONNY AND MARIE as promised in TV GUIDE!'),
	(default, 1, 'It''s the RINSE CYCLE!!  They''ve ALL IGNORED the RINSE CYCLE!!'),
	(default, 1, 'It''s today''s SPECIAL!'),
	(default, 1, 'JAPAN is a WONDERFUL planet -- I wonder if we''ll ever reach  their level of COMPARATIVE SHOPPING...'),
	(default, 1, 'Jesus is my POSTMASTER GENERAL..'),
	(default, 1, 'Join the PLUMBER''S UNION!!'),
	(default, 1, '...Just enough time to do my LIBERACE impression...'),
	(default, 1, 'Just imagine you''re entering a state-of-the-art CAR WASH!!'),
	(default, 1, 'Just to have MORE FUN, I''ll pretend I am JAMES CAGNEY and I am having  a tense, UP-TIGHT EXPERIENCE!!'),
	(default, 1, 'KARL MALDEN''S NOSE just won an ACADEMY AWARD!!'),
	(default, 1, 'Kids, don''t gross me off..  ``Adventures with MENTAL HYGIENE''''  can be carried too FAR!'),
	(default, 1, 'Kids, the seven basic food groups are GUM, PUFF PASTRY, PIZZA, PESTICIDES, ANTIBIOTICS, NUTRA-SWEET and MILK DUDS!!'),
	(default, 1, 'Laundry is the fifth dimension!!  ...um...um...  th'' washing machine  is a black hole and the pink socks are bus drivers who just fell in!!'),
	(default, 1, 'LBJ, LBJ, how many JOKES did you tell today??!'),
	(default, 1, 'Leona, I want to CONFESS things to you..  I want to WRAP you in a SCARLET ROBE trimmed with POLYVINYL CHLORIDE..  I want to EMPTY your ASHTRAYS...'),
	(default, 1, 'Let me do my TRIBUTE to FISHNET STOCKINGS...'),
	(default, 1, 'Let''s all show human CONCERN for REVEREND MOON''s legal difficulties!!'),
	(default, 1, 'Let''s climb to the TOP of that MOUNTAIN and think about STRIP MINING!!'),
	(default, 1, 'Let''s go to CHURCH!'),
	(default, 1, 'Let''s send the Russians defective lifestyle accessories!'),
	(default, 1, 'LIFE is a never-ending INFORMERCIAL!'),
	(default, 1, 'Life is selling REVOLUTIONARY HAIR PRODUCTS!'),
	(default, 1, '..  Like I always say -- nothing can beat the BRATWURST  here in DUSSELDORF!!'),
	(default, 1, 'Loni Anderson''s hair should be LEGALIZED!!'),
	(default, 1, 'Look DEEP into the OPENINGS!!  Do you see any ELVES or EDSELS...  or a HIGHBALL??...'),
	(default, 1, 'Look into my eyes and try to forget that you have a Macy''s charge card!'),
	(default, 1, 'Look!  A ladder!  Maybe it leads to heaven, or a sandwich!'),
	(default, 1, 'Look!!  Karl Malden!'),
	(default, 1, 'LOOK!!  Sullen American teens wearing MADRAS shorts and  ``Flock of Seagulls'''' HAIRCUTS!'),
	(default, 1, 'LOOK!!!  I''m WALKING in my SLEEP again!!'),
	(default, 1, 'LOU GRANT froze my ASSETS!!'),
	(default, 1, 'Make me look like LINDA RONSTADT again!!'),
	(default, 1, 'Mary Tyler Moore''s SEVENTH HUSBAND is wearing my DACRON TANK TOP  in a cheap hotel in HONOLULU!'),
	(default, 1, 'Maybe we could paint GOLDIE HAWN a rich PRUSSIAN BLUE--'),
	(default, 1, 'MERYL STREEP is my obstetrician!'),
	(default, 1, 'MMM-MM!!  So THIS is BIO-NEBULATION!'),
	(default, 1, 'Mmmmmm-MMMMMM!!  A plate of STEAMING PIECES of a PIG mixed  with the shreds of SEVERAL CHICKENS!!...  Oh BOY!!  I''m  about to swallow a TORN-OFF section of a COW''S LEFT LEG  soaked in COTTONSEED OIL and SUGAR!!  ..  Let''s see..  Next, I''ll have the GROUND-UP flesh of CUTE, BABY LAMBS  fried in the MELTED, FATTY TISSUES from a warm-blooded  animal someone once PETTED!!  ...  YUM!!  That was GOOD!!  For DESSERT, I''ll have a TOFU BURGER with BEAN SPROUTS  on a stone-ground, WHOLE WHEAT BUN!!'),
	(default, 1, 'Mr and Mrs PED, can I borrow 26.7% of the RAYON TEXTILE production  of the INDONESIAN archipelago?'),
	(default, 1, 'My Aunt MAUREEN was a military advisor to IKE & TINA TURNER!!'),
	(default, 1, 'My BIOLOGICAL ALARM CLOCK just went off..  It has noiseless  DOZE FUNCTION and full kitchen!!'),
	(default, 1, 'My CODE of ETHICS is vacationing at famed SCHROON LAKE  in upstate New York!!'),
	(default, 1, 'My DIGITAL WATCH has an automatic SNOOZE FEATURE!!'),
	(default, 1, 'My EARS are GONE!!'),
	(default, 1, 'My ELBOW is a remote FRENCH OUTPOST!!'),
	(default, 1, 'My face is new, my license is expired, and I''m under a doctor''s care!!!!'),
	(default, 1, 'My FAVORITE group is "QUESTION MARK & THE MYSTERIANS"...'),
	(default, 1, 'My forehead feels like a PACKAGE of moist CRANBERRIES in a remote  FRENCH OUTPOST!!'),
	(default, 1, 'My haircut is totally traditional!'),
	(default, 1, 'MY income is ALL disposable!'),
	(default, 1, 'My LESLIE GORE record is BROKEN..'),
	(default, 1, 'My LIBRARY CARD expired...'),
	(default, 1, 'My life is a patio of fun!'),
	(default, 1, 'My mind is a potato field...'),
	(default, 1, 'My mind is making ashtrays in Dayton....'),
	(default, 1, 'My nose feels like a bad Ronald Reagan movie...'),
	(default, 1, '..  my NOSE is NUMB!'),
	(default, 1, '..  My pants just went on a wild rampage through  a Long Island Bowling Alley!!'),
	(default, 1, 'My pants just went to high school in the Carlsbad Caverns!!!'),
	(default, 1, 'My polyvinyl cowboy wallet was made in Hong Kong by Montgomery Clift!'),
	(default, 1, 'My TOYOTA is built like a ... BAGEL with CREAM CHEESE!!'),
	(default, 1, 'My uncle Murray conquered Egypt in 53 B.C.  And I can prove it too!!'),
	(default, 1, '..  My vaseline is RUNNING...'),
	(default, 1, 'NANCY!!  Why is everything RED?!'),
	(default, 1, 'NATHAN...  your PARENTS were in a CARCRASH!!  They''re VOIDED - They COLLAPSED  They had no CHAINSAWS...  They had no MONEY MACHINES...  They did PILLS in SKIMPY GRASS SKIRTS...  Nathan, I EMULATED them...  but they were OFF-KEY...'),
	(default, 1, 'NEWARK has been REZONED!!  DES MOINES has been REZONED!!'),
	(default, 1, 'Nice decor!'),
	(default, 1, 'Not enough people play SKEE-BALL..  They''re always thinking about  COCAINE or and ALIEN BEINGS!!'),
	(default, 1, 'NOT fucking!! Also not a PACKAGE of LOOSE-LEAF PAPER!!'),
	(default, 1, 'Not SENSUOUS...  only ``FROLICSOME''''...  and in need of DENTAL WORK...  in PAIN!!!'),
	(default, 1, 'NOW do I get to blow out the CANDLES??'),
	(default, 1, 'Now I am depressed...'),
	(default, 1, 'Now I can join WEIGHT WATCHERS!'),
	(default, 1, 'Now I need a suntan, a tennis lesson, Annette Funicello and two dozen  Day-Glo orange paper jumpsuits!!'),
	(default, 1, '..  Now I think I just reached the state of HYPERTENSION that comes  JUST BEFORE you see the TOTAL at the SAFEWAY CHECKOUT COUNTER!'),
	(default, 1, 'Now I understand the meaning of ``THE MOD SQUAD''''!'),
	(default, 1, 'Now I''m being INVOLUNTARILY shuffled closer to the CLAM DIP  with the BROKEN PLASTIC FORKS in it!!'),
	(default, 1, 'Now I''m concentrating on a specific tank battle toward  the end of World War II!'),
	(default, 1, 'Now I''m having INSIPID THOUGHTS about the beautiful, round  wives of HOLLYWOOD MOVIE MOGULS encased in PLEXIGLASS CARS  and being approached by SMALL BOYS selling FRUIT..'),
	(default, 1, 'Now I''m telling MISS PIGGY about MONEY MARKET FUNDS!'),
	(default, 1, '..  Now KEN and BARBIE are PERMANENTLY ADDICTED to MIND-ALTERING DRUGS..'),
	(default, 1, 'Now KEN is having a MENTAL CRISIS because his "R.V." PAYMENTS are  OVER-DUE!!'),
	(default, 1, 'Now my EMOTIONAL RESOURCES are heavily committed to 23% of the  SMELTING and REFINING industry of the state of NEVADA!!'),
	(default, 1, 'Now that I have my ``APPLE,'''' I comprehend COST ACCOUNTING!!'),
	(default, 1, 'Now that we''re in LOVE, you can BUY this GOLDFISH for a 48% DISCOUNT.'),
	(default, 1, 'Now, I think it would be GOOD to buy FIVE or SIX STUDEBAKERS  and CRUISE for ARTIFICIAL FLAVORING!!'),
	(default, 1, 'NOW, I''m supposed to SCRAMBLE two, and HOLD th'' MAYO!!'),
	(default, 1, 'NOW, I''m taking the NEXT FLIGHT to ACAPULCO so I can write POEMS about  BROKEN GUITAR STRINGS and sensuous PRE-TEENS!!'),
	(default, 1, 'Now, let''s SEND OUT for QUICHE!!'),
	(default, 1, 'Now, my ENTIRE LIFE is flashing before my EYES as I park my DODGE  DART in your EXXON service area for a COMPLETE LUBRICATION!!'),
	(default, 1, 'O.K.!  Speak with a PHILADELPHIA ACCENT!!  Send out for CHINESE FOOD!!  Hop a JET!'),
	(default, 1, 'Of course, you UNDERSTAND about the PLAIDS in the SPIN CYCLE --'),
	(default, 1, 'Oh my GOD -- the SUN just fell into YANKEE STADIUM!!'),
	(default, 1, 'Oh, FISH sticks, CHEEZ WHIZ, GIN fizz, SHOW BIZ!!'),
	(default, 1, 'Oh, I get it!!  ``The BEACH goes on,'''' huh, SONNY??'),
	(default, 1, 'OKAY!!  Turn on the sound ONLY for TRYNEL CARPETING, FULLY-EQUIPPED R.V.''S and FLOATATION SYSTEMS!!'),
	(default, 1, 'Okay, BARBRA STREISAND, I recognize you now!!  Also EFREM ZIMBALIST, JUNIOR!!  And BEAUMONT NEWHALL!!  Everybody into th'' BATHROOM!'),
	(default, 1, 'Okay..  I''m going home to write the ``I HATE RUBIK''s CUBE  HANDBOOK FOR DEAD CAT LOVERS''''..'),
	(default, 1, 'OMNIVERSAL AWARENESS??  Oh, YEH!!  First you need 4 GALLONS of JELL-O  and a BIG WRENCH!!...  I think you drop th''WRENCH in the JELL-O as if  it was a FLAVOR, or an INGREDIENT...  ...or...I...um...  WHERE''S the  WASHING MACHINES?'),
	(default, 1, 'On SECOND thought, maybe I''ll heat up some BAKED BEANS and  watch REGIS PHILBIN..  It''s GREAT to be ALIVE!!'),
	(default, 1, 'On the other hand, life can be an endless parade of TRANSSEXUAL  QUILTING BEES aboard a cruise ship to DISNEYWORLD  if only we let it!!'),
	(default, 1, 'On the road, ZIPPY is a pinhead without a purpose, but never  without a POINT.'),
	(default, 1, '..  Once upon a time, four AMPHIBIOUS HOG CALLERS attacked a family  of DEFENSELESS, SENSITIVE COIN COLLECTORS and brought DOWN their  PROPERTY VALUES!!'),
	(default, 1, 'Once, there was NO fun...  This was before MENU planning, FASHION statements or NAUTILUS equipment...  Then, in 1985..  FUN was completely encoded in this tiny MICROCHIP..  It contain 14,768 vaguely amusing SIT-COM pilots!!  We had to wait FOUR BILLION years but we finally got JERRY LEWIS, MTV and a large selection of cream-filled snack cakes!'),
	(default, 1, '..  One FISHWICH coming up!!'),
	(default, 1, 'ONE:  I will donate my entire ``BABY HUEY'''' comic book collection  to the downtown PLASMA CENTER..  TWO:  I won''t START a BAND called ``KHADAFY & THE HIT SQUAD''''..  THREE:  I won''t ever TUMBLE DRY my FOX TERRIER again!!'),
	(default, 1, '..  or were you driving the PONTIAC that HONKED at me  in MIAMI last Tuesday?'),
	(default, 1, 'Our father who art in heaven..  I sincerely pray that SOMEBODY  at this table will PAY for my SHREDDED WHAT and ENGLISH MUFFIN..  and also leave a GENEROUS TIP...'),
	(default, 1, '..  over in west Philadelphia a puppy is vomiting..'),
	(default, 1, 'OVER the undertow!  UNDER the overpass!  Around the FUTURE  and BEYOND REPAIR!!'),
	(default, 1, 'PARDON me, am I speaking ENGLISH?'),
	(default, 1, 'Pardon me, but do you know what it means to be TRULY ONE  with your BOOTH!'),
	(default, 1, 'PEGGY FLEMING is stealing BASKET BALLS to feed the babies in VERMONT.'),
	(default, 1, '...PENGUINS are floating by...'),
	(default, 1, 'PIZZA!!'),
	(default, 1, 'Place me on a BUFFER counter while you BELITTLE several BELLHOPS  in the Trianon Room!!  Let me one of your SUBSIDIARIES!'),
	(default, 1, 'Please come home with me...  I have Tylenol!!'),
	(default, 1, 'Psychoanalysis??  I thought this was a nude rap session!!!'),
	(default, 1, 'PUMP UP th'' VOLUME!  My BAGEL TOASTER is in tune with th'' UNIVERSAL LIFE  FORCE!!'),
	(default, 1, 'PUNK ROCK!!  DISCO DUCK!!  BIRTH CONTROL!!'),
	(default, 1, 'Put FIVE DOZEN red GIRDLES in each CIRCULAR OPENING!!'),
	(default, 1, 'Quick, sing me the BUDAPEST NATIONAL ANTHEM!!'),
	(default, 1, 'QUIET!!  I''m being CREATIVE!!  Is it GREAT yet?  It''s s''posed to  SMOKEY THE BEAR...'),
	(default, 1, 'RELATIVES!!'),
	(default, 1, 'RELAX!! ... This is gonna be a HEALING EXPERIENCE!!  Besides, I work for DING DONGS!'),
	(default, 1, 'Remember, if you try to ESCAPE, many APARTMENT HOPPING ALCOHOLICS will  SIMONIZE your HALLWAYS!!  This is your LAST WARNING!!'),
	(default, 1, 'Remember, in 2039, MOUSSE & PASTA will be available  ONLY by prescription!!'),
	(default, 1, 'RHAPSODY in Glue!'),
	(default, 1, 'SANTA CLAUS comes down a FIRE ESCAPE wearing bright  blue LEG WARMERS..  He scrubs the POPE with a mild  soap or detergent for 15 minutes, starring JANE FONDA!!'),
	(default, 1, 'Send your questions to ``ASK ZIPPY'''', Box 40474, San Francisco, CA 94140, USA'),
	(default, 1, 'SHHHH!!  I hear SIX TATTOOED TRUCK-DRIVERS tossing ENGINE BLOCKS  into empty OIL DRUMS..'),
	(default, 1, 'Should I do my BOBBIE VINTON medley?'),
	(default, 1, '..  Should I get locked in the PRINCIPAL''S OFFICE today --  or have a VASECTOMY??'),
	(default, 1, 'Should I start with the time I SWITCHED personalities with a BEATNIK  hair stylist or my failure to refer five TEENAGERS to a good OCULIST?'),
	(default, 1, 'Sign my PETITION.'),
	(default, 1, 'So this is what it feels like to be potato salad'),
	(default, 1, '..  So, if we convert SUPPLY-SIDE SOYBEAN FUTURES into  HIGH-YIELD T-BILL INDICATORS, the PRE-INFLATIONARY risks  will DWINDLE to a rate of 2 SHOPPING SPREES per EGGPLANT!!'),
	(default, 1, '..  someone in DAYTON, Ohio is selling USED CARPETS to a SERBO-CROATIAN'),
	(default, 1, 'Someone is DROOLING on my collar!!'),
	(default, 1, 'Sometime in 1993 NANCY SINATRA will lead a BLOODLESS COUP on GUAM!!'),
	(default, 1, 'Sometimes a TABOO is just a good CIGAR -- or a  rare STEAK -- or a dry MARTINI!'),
	(default, 1, 'Somewhere in DOWNTOWN BURBANK a prostitute is OVERCOOKING a LAMB CHOP!!'),
	(default, 1, 'Somewhere in suburban Honolulu, an unemployed bellhop is whipping up  a batch of illegal psilocybin chop suey!!'),
	(default, 1, 'Somewhere in Tenafly, New Jersey, a chiropractor is viewing  ``Leave it to Beaver''''!'),
	(default, 1, 'Sorry, wrong ZIP CODE!!'),
	(default, 1, 'Spreading peanut butter reminds me of opera!!  I wonder why?'),
	(default, 1, 'TAILFINS!!  ...click...'),
	(default, 1, 'Talking Pinhead Blues:  Oh, I LOST my ``HELLO KITTY'''' DOLL and I get BAD reception on   channel TWENTY-SIX!!  Th''HOSTESS FACTORY is closin'' down and I just heard ZASU PITTS   has been DEAD for YEARS..  (sniff)  My PLATFORM SHOE collection was CHEWED up by th''dog, ALEXANDER   HAIG won''t let me take a SHOWER ''til Easter.. (snurf)  So I went to the kitchen, but WALNUT PANELING whup me   upside mah HAID!! (on no, no, no..  Heh, heh)'),
	(default, 1, 'TAPPING?  You POLITICIANS!  Don''t you realize that the END of the  ``Wash Cycle'''' is a TREASURED MOMENT for most people?!'),
	(default, 1, 'TATTOOED MIDGETS are using ALFREDO in their SALAMI FACTORY!'),
	(default, 1, 'Tex SEX!  The HOME of WHEELS!  The dripping of COFFEE!!  Take me  to Minnesota but don''t EMBARRASS me!!'),
	(default, 1, 'Th'' MIND is the Pizza Palace of th'' SOUL'),
	(default, 1, 'Th'' PINK SOCK... soaking... soaking... soaking...  Th'' PINK SOCK... washing... washing... washing...  Th'' PINK SOCK... rinsing... rinsing... rinsing...'),
	(default, 1, 'Thank god!!..  It''s HENNY YOUNGMAN!!'),
	(default, 1, 'That''s a decision that can only be made between you & SY SPERLING!!'),
	(default, 1, 'The appreciation of the average visual graphisticator alone is worth  the whole suaveness and decadence which abounds!!'),
	(default, 1, 'The entire CHINESE WOMEN''S VOLLEYBALL TEAM all share ONE personality --  and have since BIRTH!!'),
	(default, 1, 'The fact that 47 PEOPLE are yelling and sweat is cascading  down my SPINAL COLUMN is fairly enjoyable!!'),
	(default, 1, 'The FALAFEL SANDWICH lands on my HEAD and I become a VEGETARIAN...'),
	(default, 1, '..  the HIGHWAY is made out of LIME JELLO and my HONDA  is a barbequed OYSTER!  Yum!'),
	(default, 1, 'The Korean War must have been fun.'),
	(default, 1, '"THE LITTLE PINK FLESH SISTERS," I saw them at th'' FLUORESCENT BULB  MAKERS CONVENTION...'),
	(default, 1, 'The LOGARITHM of an ISOSCELES TRIANGLE is TUESDAY WELD!!'),
	(default, 1, '..  the MYSTERIANS are in here with my CORDUROY SOAP DISH!!'),
	(default, 1, 'The Osmonds!  You are all Osmonds!!  Throwing up on a freeway at dawn!!!'),
	(default, 1, 'The PILLSBURY DOUGHBOY is CRYING for an END to BURT REYNOLDS movies!!'),
	(default, 1, 'The PINK SOCKS were ORIGINALLY from 1952!!  But they went to MARS around 1953!!'),
	(default, 1, 'The SAME WAVE keeps coming in and COLLAPSING like a rayon MUU-MUU..'),
	(default, 1, '..The TENSION mounts as I MASSAGE your RIGHT ANKLE according to  ancient Tibetan ACCOUNTING PROCEDURES..are you NEUROTIC yet??'),
	(default, 1, 'Then, it''s off to RED CHINA!!'),
	(default, 1, 'There''s a little picture of ED MCMAHON doing BAD THINGS to JOAN RIVERS  in a $200,000 MALIBU BEACH HOUSE!!'),
	(default, 1, 'There''s a lot of BIG MONEY in MISERY if you have an AGENT!!'),
	(default, 1, 'There''s a SALE on STRETCH SOCKS down at the "7-11"!!'),
	(default, 1, 'There''s enough money here to buy 5000 cans of Noodle-Roni!'),
	(default, 1, 'These PRESERVES should be FORCE-FED to PENTAGON OFFICIALS!!'),
	(default, 1, 'They collapsed....  like nuns in the street...  they had no teen appeal!'),
	(default, 1, 'They don''t hire PERSONAL PINHEADS, Mr. Toad!'),
	(default, 1, 'This ASEXUAL PIG really BOILS my BLOOD...  He''s so..so.....URGENT!!'),
	(default, 1, 'This ASIAGO-N-DRIED TOMATO combo would taste a lot better between two  plastic SIPPER LIDS!'),
	(default, 1, 'This is a NO-FRILLS flight -- hold th'' CANADIAN BACON!!'),
	(default, 1, 'This is my WILLIAM BENDIX memorial CORNER where I worship William  Bendix like a GOD!!'),
	(default, 1, 'This is PLEASANT!'),
	(default, 1, 'This MUST be a good party -- My RIB CAGE is being painfully  pressed up against someone''s MARTINI!!'),
	(default, 1, '..  this must be what it''s like to be a COLLEGE GRADUATE!!'),
	(default, 1, 'This PIZZA symbolizes my COMPLETE EMOTIONAL RECOVERY!!'),
	(default, 1, 'This PORCUPINE knows his ZIPCODE..  And he has ``VISA''''!!'),
	(default, 1, 'This TOPS OFF my partygoing experience!  Someone I DON''T LIKE  is talking to me about a HEART-WARMING European film..'),
	(default, 1, 'Those aren''t WINOS--that''s my JUGGLER, my AERIALIST, my SWORD SWALLOWER, and my LATEX NOVELTY SUPPLIER!!'),
	(default, 1, 'Thousands of days of civilians ...  have produced a...  feeling for the aesthetic modules --'),
	(default, 1, 'Three attractive BANK ROBBERS are discussing RELIGIOUS DIFFERENCES and  MAKE-UP TECHNIQUE with them!!'),
	(default, 1, 'Today, THREE WINOS from DETROIT sold me a framed photo of  TAB HUNTER before his MAKEOVER!'),
	(default, 1, 'Toes, knees, NIPPLES.  Toes, knees, nipples, KNUCKLES...  Nipples, dimples, knuckles, NICKLES, wrinkles, pimples!!  I don''t like FRANK SINATRA or his CHILDREN.'),
	(default, 1, 'TONY RANDALL!  Is YOUR life a PATIO of FUN??'),
	(default, 1, 'Two LITTLE black dots and one BIG black dot...nice ''n'' FLUFFY!!'),
	(default, 1, 'Two with FLUFFO, hold th'' BEETS..side of SOYETTES!'),
	(default, 1, 'Uh-oh --  WHY am I suddenly thinking of a VENERABLE religious leader  frolicking on a FORT LAUDERDALE weekend?'),
	(default, 1, 'Uh-oh!!  I forgot to submit to COMPULSORY URINALYSIS!'),
	(default, 1, 'UH-OH!!  I put on ``GREAT HEAD-ON TRAIN COLLISIONS of the 50''s''''  by mistake!!!'),
	(default, 1, 'UH-OH!!  I think KEN is OVER-DUE on his R.V. PAYMENTS and HE''S  having a NERVOUS BREAKDOWN too!!  Ha ha.'),
	(default, 1, 'Uh-oh!!  I''m having TOO MUCH FUN!!'),
	(default, 1, 'UH-OH!!  We''re out of AUTOMOBILE PARTS and RUBBER GOODS!'),
	(default, 1, '...Um...Um...'),
	(default, 1, 'Used staples are good with SOY SAUCE!'),
	(default, 1, 'Vote for ME -- I''m well-tapered, half-cocked, ill-conceived and  TAX-DEFERRED!'),
	(default, 1, '..Wait ''til those  ITALIAN TEENAGERS get back to their HONDAS &  discover them to be FILLED to the BRIM with MAZOLA!!'),
	(default, 1, 'Wait..  is this a FUN THING or the END of LIFE in Petticoat Junction??'),
	(default, 1, 'Was my SOY LOAF left out in th''RAIN?  It tastes REAL GOOD!!'),
	(default, 1, 'We are now enjoying total mutual interaction in an imaginary hot tub...'),
	(default, 1, 'We have DIFFERENT amounts of HAIR --'),
	(default, 1, 'We just joined the civil hair patrol!'),
	(default, 1, 'We place two copies of PEOPLE magazine in a DARK, HUMID mobile home.  45 minutes later CYNDI LAUPER emerges wearing a BIRD CAGE on her head!'),
	(default, 1, 'Well, here I am in AMERICA..  I LIKE it.  I HATE it.  I LIKE it.  I HATE it.  I LIKE it.  I HATE it.  I LIKE it.  I HATE it.  I LIKE..  EMOTIONS are SWEEPING over me!!'),
	(default, 1, 'Well, I''m a classic ANAL RETENTIVE!!  And I''m looking for a way to  VICARIOUSLY experience some reason to LIVE!!'),
	(default, 1, 'Well, I''m INVISIBLE AGAIN..  I might as well pay a visit to the  LADIES ROOM...'),
	(default, 1, 'Well, I''m on the right planet---everyone looks like me!!!'),
	(default, 1, 'Well, O.K.  I''ll compromise with my principles because of  EXISTENTIAL DESPAIR!'),
	(default, 1, 'Were these parsnips CORRECTLY MARINATED in TACO SAUCE?'),
	(default, 1, 'What a COINCIDENCE!  I''m an authorized ``SNOOTS OF THE STARS'''' dealer!!'),
	(default, 1, 'What GOOD is a CARDBOARD suitcase ANYWAY?'),
	(default, 1, 'What I need is a MATURE RELATIONSHIP with a FLOPPY DISK...'),
	(default, 1, 'What I want to find out is -- do parrots know much about Astro-Turf?'),
	(default, 1, 'What PROGRAM are they watching?'),
	(default, 1, 'What UNIVERSE is this, please??'),
	(default, 1, 'What''s the MATTER Sid?..  Is your BEVERAGE unsatisfactory?'),
	(default, 1, 'When I met th''POPE back in ''58, I scrubbed him with a MILD SOAP  or DETERGENT for 15 minutes.  He seemed to enjoy it..'),
	(default, 1, 'When this load is DONE I think I''ll wash it AGAIN..'),
	(default, 1, 'When you get your PH.D. will you get able to work at BURGER KING?'),
	(default, 1, 'When you said ``HEAVILY FORESTED'''' it reminded me of an overdue  CLEANING BILL..  Don''t you SEE?  O''Grogan SWALLOWED a VALUABLE  COIN COLLECTION and HAD to murder the ONLY MAN who KNEW!!'),
	(default, 1, 'Where do your SOCKS go when you lose them in th'' WASHER?'),
	(default, 1, 'Where does it go when you flush?'),
	(default, 1, 'Where''s my SOCIAL WORKER?'),
	(default, 1, 'Where''s SANDY DUNCAN?'),
	(default, 1, 'Where''s th'' DAFFY DUCK EXHIBIT??'),
	(default, 1, 'Where''s the Coke machine?  Tell me a joke!!'),
	(default, 1, 'While I''m in LEVITTOWN I thought I''d like to see the NUCLEAR FAMILY!!'),
	(default, 1, 'While my BRAINPAN is being refused service in BURGER KING, Jesuit priests are DATING CAREER DIPLOMATS!!'),
	(default, 1, 'While you''re chewing, think of STEVEN SPIELBERG''S  bank account..  This will have the same effect as  two ``STARCH BLOCKERS''''!'),
	(default, 1, 'WHO sees a BEACH BUNNY sobbing on a SHAG RUG?!'),
	(default, 1, 'Who wants some OYSTERS with SEN-SEN an'' COOL WHIP?'),
	(default, 1, 'WHOA!!  I''m having a RELIGIOUS EXPERIENCE right NOW!!'),
	(default, 1, 'WHOA!!  Ken and Barbie are having TOO MUCH FUN!!  It must  be the NEGATIVE IONS!!'),
	(default, 1, 'Why am I in this ROOM in DOWNTOWN PHILADELPHIA?'),
	(default, 1, 'Why are these athletic shoe salesmen following me??'),
	(default, 1, 'WHY are we missing KOJAK?'),
	(default, 1, 'Why don''t you ever enter any CONTESTS, Marvin??  Don''t you know your own ZIPCODE?'),
	(default, 1, 'Why is everything made of Lycra Spandex?'),
	(default, 1, 'Why is it that when you DIE, you can''t take your  HOME ENTERTAINMENT CENTER with you??'),
	(default, 1, 'Why was I BORN?'),
	(default, 1, 'Will it improve my CASH FLOW?'),
	(default, 1, 'Will the third world war keep ``Bosom Buddies'''' off the air?'),
	(default, 1, 'Will this never-ending series of PLEASURABLE EVENTS never cease?'),
	(default, 1, 'With this weapon I can expose fictional characters and bring about  sweeping reforms!!'),
	(default, 1, 'With YOU, I can be MYSELF..  We don''t NEED Dan Rather..'),
	(default, 1, 'World War Three can be averted by adherence to a strictly enforced  dress code!'),
	(default, 1, 'Wow!  Look!!  A stray meatball!!  Let''s interview it!'),
	(default, 1, 'Xerox your lunch and file it under ``sex offenders!'''''),
	(default, 1, 'Yes, but will I see the EASTER BUNNY in skintight leather  at an IRON MAIDEN concert?'),
	(default, 1, 'Yes, Private DOBERMAN!!'),
	(default, 1, 'You can''t hurt me!!  I have an ASSUMABLE MORTGAGE!!'),
	(default, 1, 'You mean now I can SHOOT YOU in the back and further BLUR  th'' distinction between FANTASY and REALITY?'),
	(default, 1, 'You mean you don''t want to watch WRESTLING from ATLANTA?'),
	(default, 1, 'You must be a CUB SCOUT!!  Have you made your MONEY-DROP today??'),
	(default, 1, 'YOU PICKED KARL MALDEN''S NOSE!!'),
	(default, 1, 'You should all JUMP UP AND DOWN for TWO HOURS while I decide  on a NEW CAREER!!'),
	(default, 1, 'YOU!!  Give me the CUTEST, PINKEST, most charming little  VICTORIAN DOLLHOUSE you can find!!  An make it SNAPPY!!'),
	(default, 1, 'YOU''D cry too if it happened to YOU!!'),
	(default, 1, 'Your CHEEKS sit like twin NECTARINES above a MOUTH that knows no BOUNDS --'),
	(default, 1, 'Youth of today!  Join me in a mass rally for traditional mental attitudes!'),
	(default, 1, 'Yow!'),
	(default, 1, 'Yow!  Am I cleansed yet?!'),
	(default, 1, 'Yow!  Am I having fun yet?'),
	(default, 1, 'Yow!  Am I in Milwaukee?'),
	(default, 1, 'Yow!  Am I JOGGING yet??'),
	(default, 1, 'Yow!  And then we could sit on the hoods of cars at stop lights!'),
	(default, 1, 'Yow!  Are we in the perfect mood?'),
	(default, 1, 'Yow!  Are we laid back yet?'),
	(default, 1, 'Yow!  Are we wet yet?'),
	(default, 1, 'Yow!  Are you the self-frying president?'),
	(default, 1, 'Yow!  Did something bad happen or am I in a drive-in movie??'),
	(default, 1, 'YOW!  I can see 1987!!  PRESIDENT FORD is doing the REMAKE of "PAGAN  LOVE SONG"...he''s playing ESTHER WILLIAMS!!'),
	(default, 1, 'Yow!  I forgot my PAIL!!'),
	(default, 1, 'Yow!  I just went below the poverty line!'),
	(default, 1, 'Yow!  I like my new DENTIST...'),
	(default, 1, 'Yow!  I threw up on my window!'),
	(default, 1, 'Yow!  I want my nose in lights!'),
	(default, 1, 'Yow!  I want to mail a bronzed artichoke to Nicaragua!'),
	(default, 1, 'Yow!  I''m having a quadrophonic sensation of two winos  alone in a steel mill!'),
	(default, 1, 'Yow!  I''m imagining a surfer van filled with soy sauce!'),
	(default, 1, 'Yow!  I''m out of work...I could go into shock absorbers...or SCUBA  GEAR!!'),
	(default, 1, 'Yow!  I''m UNEMPLOYED!'),
	(default, 1, 'Yow!  Is my fallout shelter termite proof?'),
	(default, 1, 'Yow!  Is this sexual intercourse yet??  Is it, huh, is it??'),
	(default, 1, 'Yow!  It''s a hole all the way to downtown Burbank!'),
	(default, 1, 'Yow!  It''s some people inside the wall!  This is better than mopping!'),
	(default, 1, 'Yow!  Maybe I should have asked for my Neutron Bomb in PAISLEY--'),
	(default, 1, 'Yow!  Now I get to think about all the BAD THINGS I did to a BOWLING BALL  when I was in JUNIOR HIGH SCHOOL!'),
	(default, 1, 'Yow!  Now we can become alcoholics!'),
	(default, 1, 'Yow!  STYROFOAM..'),
	(default, 1, 'Yow!  Those people look exactly like Donnie and Marie Osmond!!'),
	(default, 1, 'Yow!  We''re going to a new disco!'),
	(default, 1, 'YOW!!'),
	(default, 1, 'Yow!!  "Janitor trapped in sewer uses ESP to find decayed burger"!!'),
	(default, 1, 'YOW!!  Everybody out of the GENETIC POOL!'),
	(default, 1, 'YOW!!  I am having FUN!!'),
	(default, 1, 'YOW!!  I''m in a very clever and adorable INSANE ASYLUM!!'),
	(default, 1, 'Yow!!  It''s LIBERACE and TUESDAY WELD!!  High on a HILL... driving a  LITTLE CAR...  I wanna be in that LITTLE CAR, too!!  I wanna drive off  with LIBBY and TUESDAY!'),
	(default, 1, 'YOW!!  Now I understand advanced MICROBIOLOGY  and th'' new TAX REFORM laws!!'),
	(default, 1, 'YOW!!  Now I''m playing with my HOLOGRAPHIC ATOMIC SIMULATION LASER  pinball machine!!  WORLD PEACE is in the BALANCE!!'),
	(default, 1, 'Yow!!  That''s a GOOD IDEA!!  Eating a whole FIELD of COUGH MEDICINE  should make you feel MUCH BETTER!!'),
	(default, 1, 'YOW!!  The land of the rising SONY!!'),
	(default, 1, 'YOW!!  Up ahead!  It''s a DONUT HUT!!'),
	(default, 1, 'YOW!!  What should the entire human race DO??  Consume a fifth  of CHIVAS REGAL, ski NUDE down MT. EVEREST, and have a wild  SEX WEEKEND!'),
	(default, 1, 'YOW!!!  I am having fun!!!'),
	(default, 1, 'YUGGA-HUGGA-BUGGA-TUGGA!!  HEY-HEY!!  A TRAIN STATION!!  No, a POST  OFFICE!!  An OCEAN LINER!!  No, I think it''s a CAFETERIA!!!'),
	(default, 1, 'Zippy''s brain cells are straining to bridge synapses...');
